### PR TITLE
Support new React Context and Hooks

### PR DESCRIPTION
**Pull request by fljot**
Hello, Lukáš @Kukkimonsuta 

I have finally prepared PR, thank you for waiting 😅
Tbh, updating README took most of the effort with all those general words about motivation.
I've left a few `TODO:#review:` comments here and there so you could pay attention to specific places, and commits are pretty atomic – so I hope it will be easy to review.

Best regards,
Pavel

### CODE REVIEW

**Comment by dustinlacewell** [comment]
It's a real shame this never got merged!

**Comment by fljot** [comment]
@dustinlacewell I'm sorry, I got distracted and depressed :( it's absolutely not @Kukkimonsuta's fault. I'll get myself together and update it. Nice to hear that somebody actually would need it)

**Comment by Kukkimonsuta** [comment]
Hi @dustinlacewell , I'm sorry - I've been busy for quite a while now and I sort of just threw this on @fljot by adding him as collaborator. There are bunch of TODOs, I took a quick look and I don't see anything I disagree with, so once @fljot is happy with it feel free to merge and I'll push release on npm.

**Comment by fljot** [comment]
@Kukkimonsuta I've updated everything and force-pushed.

I've left only single TODO, and it's rather about hypothetical extra Provider API – doesn't really need attention atm. https://github.com/Kukkimonsuta/inversify-react/pull/13/commits/d6f91ddb57f3306bb80cbf49d5d52f2980665df2

I've bumped version to a loud "1.0.0" to signify certain breaking changes (per semver, given that `@provide` was dropped and React >= 16.3 is required now to support "New" React Context API). Also I think there's not much to add, so it will likely stay like this for quite some time.

**Comment by Kukkimonsuta** [comment]
Thank you! Merged & published on npm.

**Pull request merged**
